Repository serudda/reward-system, pull requests merged in 2023-03, with the labels that each got.

#57 [RS-54] Create models
  .eslintrc.cjs
  apps/main/.eslintrc.cjs
  apps/main/package.json
  apps/main/prisma/schema.prisma
  package.json
  turbo.json
Labels: Enhancement, DB

#64 [RS-62] Create /wallet command
  apps/bot/package.json
  apps/bot/src/events/interactionCreate.ts
  apps/bot/src/events/messageCreate.ts
  apps/bot/src/events/ready.ts
  apps/bot/src/functions.ts
  apps/bot/src/handlers/Command.ts
  apps/bot/src/handlers/Event.ts
  apps/bot/src/i18n/en.json
  apps/bot/src/index.ts
  apps/bot/src/slashCommands/embed.ts
  apps/bot/src/slashCommands/ping.ts
  apps/bot/src/slashCommands/wallet.ts
  apps/bot/src/types.d.ts
  apps/nextjs/package.json
  packages/api/src/router/user.ts
  packages/auth/src/auth-options.ts
  packages/config/eslint/index.js
  pnpm-lock.yaml
  turbo.json
Labels: Enhancement

#68 [RS-63] Implement /give-coins command
  apps/bot/src/i18n/en.json
  apps/bot/src/slashCommands/giveCoins.ts
  apps/bot/src/slashCommands/wallet.ts
  packages/api/src/router/user.ts
  packages/db/prisma/schema.prisma
Labels: Enhancement, Discord

#123 [RS-71] FInal Config
  .github/workflows/pull_request.yml
  README.md
  apps/bot/README.md
Labels: Enhancement, Discord

#124 [RS-71] remove an extra }
  .github/workflows/pull_request.yml
Labels: Enhancement

#152 [RS-70] Implement giving coins reacting with an specific emoji
  .env.example
  apps/bot/src/events/interactionCreate.ts
  apps/bot/src/events/messageCreate.ts
  apps/bot/src/events/messageReaction.ts
  apps/bot/src/index.ts
  packages/api/src/router/bot.ts
Labels: Enhancement, Discord

#153 feat: first version of the pay command
  apps/bot/package.json
  apps/bot/src/i18n.ts
  apps/bot/src/i18n/en.json
  apps/bot/src/slashCommands/pay.ts
  packages/api/src/router/user.ts
  packages/api/src/utils/functions.ts
  pnpm-lock.yaml
Labels: Enhancement
